[package]
name = "yagbe"
version = "0.1.0"
authors = ["Peter Arato <it.arato@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["ttf"]
